name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  init-workflow:
    name: Initialisation du workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo "Le job est en cours."

  project-build:
    name: Construction du JAR Java
    runs-on: ubuntu-latest
    needs: init-workflow
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration du JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compilation des sources Java
        run: |
          javac -d out src/*.java src/**/*.java
          cd out
          ls -al

      - name: Création du JAR
        run: |
          ls -al
          jar -cvfm "out/ecfpoo.jar" "src/Manifest.txt" -C out .
          jar -tf out/ecfpoo.jar

      - name: Upload du JAR
        uses: actions/upload-artifact@v4
        with:
          name: ecfpoo.jar
          path: out/ecfpoo.jar

      - run: echo "Le statut de ce job est ${{ job.status }}."

      - name: Analyse SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-build-image-push:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs:
      - project-build
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Qemu
        uses: docker/setup-qemu-action@v1

      - name: Configuration de Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Connexion à Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Construction et envoi
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/ecfpoo:latest


      - run: echo "Le statut de ce job est ${{ job.status }}."
